CREATE SEQUENCE "SEC_PERSONA" minvalue 1 start with 1 increment by 1;

CREATE TABLE "DB_SEMILLERO"."PERSONA" 
   (	
   	"P_ID" NUMBER(10) NOT NULL,
    "P_NOMBRE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "P_TIPO_DOCUMENTO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
    "P_DOCUMENTO" NUMBER(13,0) NOT NULL ENABLE, 
    "P_FECHA_NACIMIENTO" DATE NOT NULL ENABLE,
	 CONSTRAINT "PERSONA_TIPO_DOCUMENTO" CHECK (P_TIPO_DOCUMENTO IN ('C.C', 'T.I', 'E')) ENABLE,
   CONSTRAINT "PK_PERSONA" PRIMARY KEY (P_ID)
   );
   
   
   