CREATE SEQUENCE "SEC_PERSONA_COMIC" minvalue 1 start with 1 increment by 1;
   
CREATE TABLE "DB_SEMILLERO"."PERSONA_COMIC" (
  "PC_ID" NUMBER(10) NOT NULL ENABLE, 
	"PC_ID_PERSONA" NUMBER(10) NOT NULL ENABLE, 
	"PC_ID_COMIC" NUMBER(10) NOT NULL ENABLE,
  "PC_FECHA_VENTA" DATE NOT NULL ENABLE,
   CONSTRAINT "PC_FK_ID_PERSONA" FOREIGN KEY (PC_ID_PERSONA) REFERENCES PERSONA(P_ID),
   CONSTRAINT "PC_FK_ID_COMIC" FOREIGN KEY (PC_ID_COMIC) REFERENCES COMIC(SCID),   
	 CONSTRAINT "PC_PK_ID" PRIMARY KEY (PC_ID));